// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOb5r7Q2URMgkyLs6kqbuk515Z1tR7m0c',
    appId: '1:332162346440:web:5584a9a305f8cd5aaea4fd',
    messagingSenderId: '332162346440',
    projectId: 'projet1-cfe3f',
    authDomain: 'projet1-cfe3f.firebaseapp.com',
    storageBucket: 'projet1-cfe3f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpyyLeDA0DD23hMuBMhaOCbwVw1T3drvs',
    appId: '1:332162346440:android:4e8315fab50a38b3aea4fd',
    messagingSenderId: '332162346440',
    projectId: 'projet1-cfe3f',
    storageBucket: 'projet1-cfe3f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTr8c5qmpp4RlA1VHZga0ExyaLXaNW4G4',
    appId: '1:332162346440:ios:af4ecbd9ce415f4daea4fd',
    messagingSenderId: '332162346440',
    projectId: 'projet1-cfe3f',
    storageBucket: 'projet1-cfe3f.appspot.com',
    iosBundleId: 'com.example.deyin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTr8c5qmpp4RlA1VHZga0ExyaLXaNW4G4',
    appId: '1:332162346440:ios:2346d2b33c381738aea4fd',
    messagingSenderId: '332162346440',
    projectId: 'projet1-cfe3f',
    storageBucket: 'projet1-cfe3f.appspot.com',
    iosBundleId: 'com.example.deyin.RunnerTests',
  );
}
